version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: water-sort-mongo-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: watersort
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - water-sort-network

  # Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: water-sort-backend-dev
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://admin:password123@mongo:27017/watersort?authSource=admin
      DB_NAME: watersort
      CORS_ORIGINS: http://localhost:3000,http://localhost
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - water-sort-network

  # Frontend (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: water-sort-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - water-sort-network

volumes:
  mongo_data_dev:

networks:
  water-sort-network:
    driver: bridge