[build]
  base = "frontend/"
  publish = "frontend/build"
  command = "yarn build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.herokuapp.com"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200